# Generated by Django 3.2.25 on 2024-09-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('fiction', 'Action'), ('Thriller', 'Thriller')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='run_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
